### ISSUE TITLE
pip doesn't work

### ISSUE THREAD

**Issue by serverhorror** [python-xy/python-xy.github.io#12]
Hi,

haven't seen a commit for a bunch of years and I'm currently facing an issue:

```
C:\Users\...>python
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pip\__init__.py", line 19, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import (
ImportError: No module named urllib3.exceptions
>>> exit()
```

The file required to load `pip._vendor.requests.packages.urllib3.exceptions`  doesn't even exist. So given the silence here forgive me if I ask: Is this project still alive?

If it is not active any more, may I suggest to archive this repository: https://help.github.com/articles/archiving-a-github-repository/

**Comment by serverhorror** [comment]
Cleaning up old issues on my profile
